version: '3'

services:
  postgres:
    image: "postgres:10"
    environment:
      - POSTGRES_PASSWORD=askbotPW
    ports:
      - 5432
    volumes:
    - ./postgres_init.sql:/docker-entrypoint-initdb.d/postgres_init.sql

  redis:
    image: redis:5
    ports:
     - 6397

  askbot:
    image: "askbot:latest_redis"
    ports:
      - "8000:80"
    depends_on:
      - postgres
    environment:
    - DATABASE_URL=postgres://askbot:askB0T!@postgres/askbottest
    - ADMIN_PASSWORD=admin
    - SECRET_KEY=123456789
    - WAIT_HOSTS=postgres:5432

# vim:ts=2:sw=2:sts=2:expandtab
